### ISSUE TITLE
Fails on OSX

### ISSUE THREAD

**Issue by phpmycoder** [clyfish/zerosprites#2]
Running `./sprite.sh test` where `./test` is a directory of (more than 8) PNG files on OSX 10.8.4 produces:

```
awk: can't open file input_btree.txt.info
 source line number 1
awk: can't open file input_btree.txt.info
 source line number 1
awk: can't open file input_btree.txt.info
 source line number 1
convert: invalid argument for option `-geometry': ++ @ error/convert.c/ConvertImageCommand/1624.
```

Digging into the `$tmpdir` reveals indeed that `input_btree.txt.info` does not exist. This is because neither `./blobb` nor `./btree` can be executed on OSX. I tested on my Ubuntu machine and sure enough the bash script worked. When invoked alone, the blobb binary produced a usage message when passed `--help`.

I assume that the binaries in this repo were compiled on a Linux machine, so I set out to find the original src so that I could compile them for Darwin. I presume that [this BloBB](http://vlsicad.eecs.umich.edu/BK/BloBB/) is the one you used in your project. According to the docs, only version 1.0 supports the `-fx` flag that you use on `./blobb`, so I assumed it was the version you compiled into this repo. However, `make`-ing this version doesn't produce the `btree` binary (and the tar didn't have a cpp for btree) that your bash script needs.

Are there any plans to include the source of these binaries in the repo so they can be compiled on Linux and OSX? If not, can you point me in the right direction of the implementation of `blobb` and `btree`, which you compiled for the repo?

Thanks!

**Comment by mems** [comment]
If you need the source code of `btree`, it here: http://eda.ee.ntu.edu.tw/research.htm (require an account)

**Comment by clyfish** [comment]
@mems , I knew the source code, but it's an old version.

**Comment by mems** [comment]
`btree` is the same version as "B*-tree Version 2.2 (Jul. 22, 2006) (Oct. 6, 2006)" (`btree_linux.exe`). The version 2.0b source code is available and can be compiled on OSX with the following makefile (from v1.0): 
```
#Project: B*-tree based floorplanning/placement
#Advisor: Yao-Wen Chang  <ywchang@cis.nctu.edu.tw>
#Author:  Jer-Ming Hsu	 <barz@cis.nctu.edu.tw>
#	  Hsun-Cheng Lee <gis88526@cis.nctu.edu.tw>
#Sponsors: NSC, Taiwan; Arcadia, Inc; UMC Corp.
#Version: 1.0
#Date:    7/19/2000

.SUFFIXES: .cc .o
SHELL=/bin/sh
CXX=g++
DEBUG= -g
OPT= -O2 -DNDEBUG
CXXFLAGS= -c $(DEBUG) $(OPT)
LDFLAGS= 

###########################################################################

LIBS = -lstdc++
OBJS = fplan.o sa.o
B_OBJS  = btree.o btree_main.o $(OBJS)
SRCS = ${OBJS:%.o=%.cc}

all:    btree 

btree: $(B_OBJS)
	$(CXX) -o btree $(B_OBJS) $(LIBS) $(LDFLAGS)

%.o : %.cc %.h fplan.h btree.h
	$(CXX) $*.cc $(CXXFLAGS)

%.o : %.cc  fplan.h btree.h
	$(CXX) $*.cc $(CXXFLAGS)

clean: 
	rm -f *.o btree *~

compact : btree
	strip $?
```

Plus few adjustments (to fix `fplan.cc:26:21: error: addition of default argument on redeclaration makes this constructor a default constructor`).

For file `fplan.cc`:
```
26c26
< FPlan::FPlan(double calpha=1){
---
> FPlan::FPlan(double calpha){
```
And for file `fplan.h`:
```
56c56
<     FPlan(double calpha);
---
>     FPlan(double calpha=1);
```

**Comment by clyfish** [comment]
There is no source code of btree version 2.2.

**Comment by mems** [comment]
Maybe you can contact authors:

- Yao-Wen Chang  <ywchang@cis.nctu.edu.tw>
- Tung-Chieh Chen <donnie@eda.ee.ntu.edu.tw>

Or other peoples how worked on the project:

- Jer-Ming Hsu   <barz@cis.nctu.edu.tw>
- Hsun-Cheng Lee <gis88526@cis.nctu.edu.tw>
