### ISSUE TITLE
Problem generating css code

### ISSUE THREAD

**Issue by Niklas81** [clyfish/zerosprites#3]
When running this on my computer as a command-line tool, sprites.txt isn't generated properly. I only get a list of the file-names and two coordinates, e.g.:

butterfly-48.png 0 0
care-32.png 49 0
cloud_arrow_up-16.png 49 33
date_from.png 0 50
date_to.png 27 50
gps-20-orange.png 66 33
gps-20.png 61 56

the command I run, from the folder where the images are, is:
/home/user/path/to/script/sprites.sh 1 *

Also, there seems to be a problem with the on-line version: If you select to also generate png8, there is no config info, and no css-code is generated.

**Comment by clyfish** [comment]
Sorry, I forgot install pngnq on the new vps.
The sprites.txt is correct. You can use imagemagick to get the dimension of the images.

**Comment by Niklas81** [comment]
Ok, how would I go about generating the css data file using imagemagick?

**Comment by clyfish** [comment]
Use identify command from imagemagick to get the width and height of the images, then you can generate the css.
http://stackoverflow.com/questions/9207965/parse-image-size-from-identify-command

**Comment by Niklas81** [comment]
Not really getting it.. Isn't the whole purpose with Zerosprites to generate css code along with an images sprite containing all the images? Basically, what I was hoping for was a simple command declaring input files and output file, e.g.:

imagemagick -c sprites.txt image.png output.css

How does the online version do it? My purpose for using this little tool was to simplify workflow, not complicate it by having to learn/hack imagemagick.. :)

**Comment by clyfish** [comment]
https://github.com/clyfish/zerosprites/blob/master/txt2css.sh
Added `txt2css.sh` for you.

**Comment by Niklas81** [comment]
Many thanks kind sir! :+1:
