### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Milewski** [clyfish/zerosprites#4]
im getting error 

./sprites.sh: line 40: 17642 Killed                  $RECTPACK -qb0 -i `awk '{if(NR!=1){printf ","}printf "%s",$2"x"$3}' input.txt` > output_rectpack.txt

**Comment by clyfish** [comment]
It's OK.

Sprites.sh first tries to find the optimal solution using rectpack for 20 seconds, then falls back to btree to find a sub-optimal solution.

**Comment by Milewski** [comment]
is it normal to wait for up to 3 hours to generate a set of 900 images?

**Comment by clyfish** [comment]
You can turn down `times` and `maxIte`(parameters of btree) to reduce the time at line 49 of sprites.sh.
